name: itemsadder_topminions
version: '3.0.5'
main: com.itemsadder_topminions.itemsadder_topminions
api-version: '1.20'
depend: [ItemsAdder, TopMinion]

commands:
  iatopminions:
    description: Reload config files for ItemsAdder TopMinions integration
    usage: /<command> reload
    permission: itemsadder_topminions.reload
  globalcraft:
    description: Opens the global crafting menu
    usage: /globalcraft
  minioncraft:
    description: Opens a specific minion crafting menu
    usage: /minioncraft <type> <material> <level>

permissions:
  itemsadder_topminions.reload:
    default: op
