name: itemsadder_topminions
version: '3.0.1'
main: com.itemsadder_topminions.itemsadder_topminions
api-version: '1.20'
depend: [ItemsAdder, TopMinion]

commands:
  iatopminions:
    description: Reload config files for ItemsAdder TopMinions integration
    usage: /<command> reload
    permission: itemsadder_topminions.reload

permissions:
  itemsadder_topminions.reload:
    default: op
